// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AgreementController from "./agreement_controller"
application.register("agreement", AgreementController)

import DadataController from "./dadata_controller"
application.register("dadata", DadataController)

import ButtonsController from "./buttons_controller"
application.register("buttons", ButtonsController)

import PhoneMaskController from "./phone_mask_controller"
application.register("phone_mask", PhoneMaskController)

import NoticesController from "./notices_controller"
application.register("notices", NoticesController)
