plugins:
  - rubocop-performance
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'bin/*'
    - 'app/services/report_service.rb'
    - 'vendor/**/*'
    - 'app/jobs/abandoned_order_reminder_job.rb'
    - 'config/initializers/filter_parameter_logging.rb'
    - 'config/deploy.rb'
    - 'app/services/statistics_service.rb'

Style/StringLiterals:
  Exclude:
    - 'config/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/models/order.rb'
    - 'app/models/user.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'config/routes.rb'
    - 'config/routes/admin.rb'

Style/Documentation:
  Enabled: false

# Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
Layout/SpaceInsideArrayLiteralBrackets:
   Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
