services:
  pg:
    image: postgres:16.1
    container_name: miniapp-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: Europe/Moscow
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - net

  miniapp:
    tty: true
    stdin_open: true
    image: miniapp
    build: .
    container_name: miniapp
    hostname: miniapp
    env_file: ./.env
    depends_on:
      - pg
      - redis
      - sidekiq
    volumes:
      - gems:/usr/local/bundle
      - .:/app
    networks:
      net:
      proxy-net:
        ipv4_address: 172.29.0.10
      s3:
        ipv4_address: 172.20.0.5
    extra_hosts: "${MINIO_DOMAIN}:${MINIO_IP}"
    restart: always

  sidekiq:
    tty: true
    stdin_open: true
    image: miniapp
    build: .
    container_name: miniapp-sidekiq
    hostname: miniapp-sidekiq
    env_file: ./.env
    depends_on:
      - pg
      - redis
    volumes:
      - gems:/usr/local/bundle
      - .:/app
    command: bundle exec sidekiq
    networks:
      net:
      s3:
        ipv4_address: 172.20.0.6
    extra_hosts: "${MINIO_DOMAIN}:${MINIO_IP}"
    restart: always

  redis:
    image: redis:latest
    container_name: miniapp-redis
    command: redis-server
    restart: unless-stopped
    networks:
      - net
    volumes:
      - redis:/data

volumes:
  db_data:
  redis:
  gems:

networks:
  net:
  proxy-net:
    external: true
  s3:
    external: true