services:
  psql:
    image: postgres:16.1
    container_name: webapp-psql
    hostname: psql
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Moscow
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - net

  webapp:
    image: webapp
    build: .
    container_name: webapp
    hostname: webapp
    env_file: ./.env
    depends_on:
      - psql
      - redis
      - sidekiq
    volumes:
      - gems:/usr/local/bundle
      - .:/app
    networks:
      net:
      proxy-net:
        ipv4_address: 172.29.0.3
    restart: always

  sidekiq:
    image: webapp
    build: .
    container_name: webapp-sidekiq
    hostname: webapp-sidekiq
    env_file: ./.env
    depends_on:
      - psql
      - redis
    volumes:
      - gems:/usr/local/bundle
      - .:/app
    command: bundle exec sidekiq
    networks:
      net:
    restart: always

  redis:
    image: redis:latest
    container_name: webapp-redis
    command: redis-server
    restart: unless-stopped
    networks:
      - net
    volumes:
      - redis:/data

volumes:
  db_data:
  redis:
  gems:

networks:
  net:
  proxy-net:
    external: true