services:
  base: &base
    tty: true
    stdin_open: true
    image: s-miniapp
    build: .
    env_file: ./.env
    depends_on:
      - pg
      - redis
    volumes:
      - gems:/usr/local/bundle
      - .:/app
    networks:
      net:
    restart: always

  s-miniapp:
    <<: *base
    container_name: s-miniapp
    hostname: s-miniapp
    networks:
      proxy-net:
        ipv4_address: 172.29.0.11
      s3:
        ipv4_address: 172.20.0.7
    extra_hosts:
      - "${MINIO_DOMAIN}:${MINIO_IP}"

  sidekiq:
    <<: *base
    container_name: s-miniapp-sidekiq
    hostname: s-miniapp-sidekiq
    command: bundle exec sidekiq
    networks:
      s3:
        ipv4_address: 172.20.0.8
    extra_hosts:
      - "${MINIO_DOMAIN}:${MINIO_IP}"

  pg:
    image: postgres:16.1
    hostname: pg
    container_name: s-miniapp-pg
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Moscow
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - net
    restart: unless-stopped

  redis:
    image: redis:7-alpine3.21
    container_name: s-miniapp-redis
    command: redis-server
    networks:
      - net
    volumes:
      - redis:/data
    restart: unless-stopped

volumes:
  db_data:
  redis:
  gems:

networks:
  net:
  proxy-net:
    external: true
  s3:
    external: true