services:
  base: &base
    image: s-miniapp
    build: .
    env_file: ./.env
    volumes:
      - gems:/usr/local/bundle
      - .:/app

  s-miniapp:
    <<: *base
    tty: true
    stdin_open: true
    container_name: s-miniapp
    hostname: s-miniapp
    entrypoint: ["./bin/docker-entrypoint"]
    depends_on:
      - pg
      - redis
    networks:
      net:
      proxy-net:
        ipv4_address: 172.29.0.11
      # s3:
      #   ipv4_address: 172.20.0.7
    # extra_hosts:
    #   - "${MINIO_DOMAIN}:${MINIO_IP}"
    restart: always

  sidekiq:
    <<: *base
    container_name: s-miniapp-sidekiq
    hostname: s-miniapp-sidekiq
    entrypoint: []
    command: >
      bash -c "bundle exec sidekiq -q default -q mailings & 
               bundle exec sidekiq -q telegram_bot -c 1 &&
               wait"
    depends_on:
      - pg
      - redis
    networks:
      net:
      # s3:
      #   ipv4_address: 172.20.0.8
    # extra_hosts:
    #   - "${MINIO_DOMAIN}:${MINIO_IP}"
    restart: always

  pg:
    image: postgres:16.1
    container_name: s-miniapp-pg
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Moscow
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - net
    restart: unless-stopped

  redis:
    image: redis:7.4.2-alpine3.21
    container_name: s-miniapp-redis
    command: redis-server
    networks:
      - net
    volumes:
      - redis:/data
    restart: unless-stopped

volumes:
  db_data:
  redis:
  gems:

networks:
  net:
  proxy-net:
    external: true
  # s3:
  #   external: true