services:
  pg:
    image: postgres:16.1
    container_name: s-miniapp-pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: Europe/Moscow
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - net
    restart: unless-stopped

  s-miniapp:
    tty: true
    stdin_open: true
    image: s-miniapp
    build: .
    container_name: s-miniapp
    env_file: ./.env
    depends_on:
      - pg
      - redis
      - sidekiq
    volumes:
      - gems:/usr/local/bundle
      - .:/app
    networks:
      net:
      proxy-net:
        ipv4_address: 172.29.0.11
      s3:
        ipv4_address: 172.20.0.5
    extra_hosts:
      - "${MINIO_DOMAIN}:${MINIO_IP}"
    restart: always

  sidekiq:
    tty: true
    stdin_open: true
    image: s-miniapp
    build: .
    container_name: s-miniapp-sidekiq
    env_file: ./.env
    depends_on:
      - pg
      - redis
    volumes:
      - gems:/usr/local/bundle
      - .:/app
    command: bundle exec sidekiq
    networks:
      net:
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: s-miniapp-redis
    command: redis-server
    networks:
      - net
    volumes:
      - redis:/data
    restart: unless-stopped

volumes:
  db_data:
  redis:
  gems:

networks:
  net:
  proxy-net:
    external: true
  s3:
    external: true