services:
  base: &base
    image: miniapp
    build: .
    env_file: ./.env
    volumes:
      - gems:/usr/local/bundle
      - .:/app

  miniapp:
    <<: *base
    container_name: miniapp
    hostname: miniapp
    depends_on:
      - pg
      - redis
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    networks:
      net:
      proxy-net:
        ipv4_address: 172.29.0.10
    restart: always


  sidekiq:
    <<: *base
    container_name: miniapp-sidekiq
    hostname: miniapp-sidekiq
    depends_on:
      - pg
      - redis
    # command: ['bundle', 'exec', 'sidekiq']
    command: >
      sh -c "SIDEKIQ_QUEUE=telegram_bot bundle exec sidekiq -q telegram_bot -c 1 &
             bundle exec sidekiq -q default &&
             wait"
    networks:
      net:
    restart: always

  pg:
    image: postgres:16.1
    container_name: miniapp-pg
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Moscow
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - net
    restart: unless-stopped

  redis:
    image: redis:7.4.2-alpine3.21
    container_name: miniapp-redis
    command: redis-server
    networks:
      - net
    volumes:
      - redis:/data
    restart: unless-stopped

volumes:
  db_data:
  redis:
  gems:

networks:
  net:
  proxy-net:
    external: true