services:
  base: &base
    image: miniapp
    build: .
    env_file: ./.env
    depends_on:
      - pg
      - redis
    volumes:
      - gems:/usr/local/bundle
      - .:/app
    networks:
      net:
    restart: always

  miniapp:
    <<: *base
    container_name: miniapp
    hostname: miniapp
    networks:
      proxy-net:
        ipv4_address: 172.29.0.10


  sidekiq:
    <<: *base
    container_name: miniapp-sidekiq
    hostname: miniapp-sidekiq
    command: bundle exec sidekiq

  pg:
    image: postgres:16.1
    container_name: miniapp-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Moscow
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      net:

  redis:
    image: redis:7-alpine3.21
    container_name: miniapp-redis
    command: redis-server
    restart: unless-stopped
    networks:
      - net
    volumes:
      - redis:/data

volumes:
  db_data:
  redis:
  gems:

networks:
  net:
  proxy-net:
    external: true