// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConfirmController from "./confirm_controller"
application.register("confirm", ConfirmController)

import DarkController from "./dark_controller"
application.register("dark", DarkController)

import MenuBtnController from "./menu_btn_controller"
application.register("menu-btn", MenuBtnController)

import ModalBtnController from "./modal_btn_controller"
application.register("modal-btn", ModalBtnController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)
