// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NoticesController from "../controllers/notices_controller"
application.register("notices", NoticesController)

import ConfirmController from "./confirm_controller"
application.register("confirm", ConfirmController)

import DarkController from "./dark_controller"
application.register("dark", DarkController)

import MenuBtnController from "./menu_btn_controller"
application.register("menu-btn", MenuBtnController)

import ModalBtnController from "./modal_btn_controller"
application.register("modal-btn", ModalBtnController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ChartRevenueController from "./chart_revenue_controller"
application.register("chart-revenue", ChartRevenueController)

import ChartOrdersController from "./chart_orders_controller"
application.register("chart-orders", ChartOrdersController)

import ChartSoldController from "./chart_sold_controller"
application.register("chart-sold", ChartSoldController)

import ChartRepeatController from "./chart_repeat_controller"
application.register("chart-repeat", ChartRepeatController)

import ChartUsersController from "./chart_users_controller"
application.register("chart-users", ChartUsersController)
